<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>ApolloNET</AssemblyName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Jimbl\Jimbl.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="apollo.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="apollo.so">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
