<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <PublishAot>true</PublishAot>
        <AssemblyName>apollo-spc-program</AssemblyName>
        
        <StripSymbols>false</StripSymbols>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Jimbl\Jimbl.csproj" />
      <ProjectReference Include="..\Apollo\Apollo.csproj" />
      <ProjectReference Include="..\SDL2\SDL2.csproj" />
    </ItemGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
        <DefineConstants>LINUX</DefineConstants>
    </PropertyGroup>

</Project>
